<?php
/*======================================================================*\
|| #################################################################### ||
|| # Package - Joomla Template based on YJSimpleGrid Framework          ||
|| # Copyright (C) since 2007  Youjoomla.com. All Rights Reserved.      ||
|| # license - PHP files are licensed under  GNU/GPL V2                 ||
|| # license - CSS  - JS - IMAGE files  are Copyrighted material        ||
|| # bound by Proprietary License of Youjoomla.com                      ||
|| # for more information visit http://www.youjoomla.com/license.html   ||
|| # Redistribution and  modification of this software                  ||
|| # is bounded by its licenses                                         ||
|| # websites - http://www.youjoomla.com | http://www.yjsimplegrid.com  ||
|| #################################################################### ||
\*======================================================================*/
defined( '_JEXEC' ) or die( 'Restricted index access' );
/*  
  !!! DO NOT EDIT THIS FILE. IT MIGHT BE CHANGED ON UPDATE
  this file is custom for this template only. if you wish to edit or add 
  own code to the template, use template_name/custom/yjsg_custom_params.php
  
*/
/*
	the $cc_css variable is for custom link color. you can use it to style any HTML elements
	see instructions here:
	http://www.yjsimplegrid.com/documentation/advanced/elements-styling-based-on-link-color.html
*/
	
$cc_css ="a,.highlight,[class*='facolor'].fa:before{color:".$style_color.";}";
$cc_css .="::selection{background:".$style_color.";}";
$cc_css .="::-moz-selection{background:".$style_color.";}";
$cc_css .="[class*='yjsg-button-color']{background:".$style_color.";}[class*='yjsg-button-color']:hover{background:".$yjsg_color->darker('5%').";}";
$cc_css .="#typosticky.yjsg-sticky.fixed{max-width:".$css_width.$css_widthdefined.";margin:0 auto;padding:15px;}";
$cc_css .=".yjsg-sub-heading,.yjsg-sticky-menu a.active-scroll,[data-sticky-block] a.active-scroll:before{border-color:".$style_color.";}";
$cc_css .="[class*='facolor'].fa:before{color:".$style_color.";}";
/* color */
$cc_css .="dt.result-title a:hover,.yjsg1 .module_title,.yjsg3 .module_title,.yjsg5 .module_title,.bottom-holder a:hover,.bdiscount h4 .discount,.bdiscount h4 .bruno-price,.bbestsellersbottom a span,.bbestsellersbottom a:hover,.bblog .yjme_item a.item_title:hover,.bnewsletter p span,.binfos .yjsg-col-1-3-in:hover span,.k2custom h4 span,div.itemAuthorBlock h3.itemAuthorName a:hover,a.moduleItemTitle:hover,div.k2LatestCommentsBlock ul li span.lcComment:hover,.k2CategoriesListBlock ul li a:hover,#k2Container .yjk2-title a:hover,.hikashop_category_name a:hover,span.hikashop_product_price,.hikashop_product_name a:hover,#hikashop_checkout_login_left_part li a:hover,ul.yjsgmenu div.yj_menu_module_holder a:hover{color:".$style_color.";}";
$cc_css .="div.k2CategoriesListBlock ul li.activeCategory a,div.k2CategoriesListBlock ul li.activeCategory a:hover,ul.yjsgmenu a.holdsgroupTitle{color:".$style_color."!important;}";
/* background */
$cc_css .=".yjsgmenu li.level0 > a.activepath,.yjsgmenu li.level0 > a:hover,.yjsgmenu li.level0 > a:focus,.yjsgmenu li.level0 > span > a.activepath,.yjsgmenu li.level0 > span > a:hover,.yjsgmenu li.level0 > span > a:focus,.yjsgmenu a.activepath,.yjsgmenu a:hover,.yjsgmenu a:focus,.yjsgmenu li:hover > .child a,.yjsg-pager-links .pager li.previous > a:hover,.yjsg-pager-links .pager li.next> a:hover,.button,a.readon,.button-color,.button-dark:hover,.button-white:hover,.search-trigger span,.bcart .hikashop_cart,.slide-price,.slidersfx-yjsgsfx-bslides ul.yjsgsliderPagination li.active a,.slidersfx-yjsgsfx-bslides ul.yjsgsliderPagination li a:hover,.tabssfx-yjsgsfx-bproducts div.tabpills ul.yjsgsliderPaginationTabs li a:hover,.tabssfx-yjsgsfx-bproducts div.tabpills ul.yjsgsliderPaginationTabs li.active a,.slidersfx-yjsgsfx-bbestsellers ul.yjsgsliderPagination li.active a,.slidersfx-yjsgsfx-bbestsellers ul.yjsgsliderPagination li a:hover,.slidersfx-yjsgsfx-btestemonials a.yjsgsliderNav:hover,.binfos .yjsg-col-1-3-in:hover,.yj-hover-effect,div.itemCommentsForm form input#submitCommentButton,.hikashop_listing_img_title .yj-shop-icon,#hikashop_checkout_login_left_part .hikashop_cart_input_button,#hikashop_checkout_login_right_part .hikashop_cart_input_button,#hikashop_checkout_coupon .hikashop_cart_input_button,.hikashop_products_pagination .list-footer a.pagenav:hover,.hikashop_subcategories_pagination .list-footer a.pagenav:hover,.list-footer span.pagenav:hover,.hikashop_subcategories_pagination .list-footer span.pagenav:hover,.list-footer a.pagenav:hover{background:".$style_color.";}";
$cc_css .=".bsearch .yjsg-element-holder .button{background:".$style_color."!important;}";
/* border */
$cc_css .=".tabssfx-yjsgsfx-bproducts div.tabpills ul.yjsgsliderPaginationTabs li a:hover,.tabssfx-yjsgsfx-bproducts div.tabpills ul.yjsgsliderPaginationTabs li.active a,.slidersfx-yjsgsfx-btestemonials a.yjsgsliderNav:hover,.hikashop_products_pagination .list-footer a.pagenav:hover,.hikashop_subcategories_pagination .list-footer a.pagenav:hover,.list-footer span.pagenav:hover,.hikashop_subcategories_pagination .list-footer span.pagenav:hover,.list-footer a.pagenav:hover{border-color:".$style_color.";}";

/*JS IMAGE EFFECT */
$YjsgCustomJS	= array();
$YjsgCustomJS[] = $yj_site.'src/styles.js';

/* K2 CSS */
if (JFactory::getApplication()->input->get( 'option' ) == 'com_k2' 
	|| JModuleHelper::getModule( 'k2_content' )
	|| JModuleHelper::getModule( 'k2_tools' )
	|| JModuleHelper::getModule( 'k2_comments' )
	){
		$document->addStyleSheet($yj_site.'css/customk.css');
}

/* HIKASHOP CSS */
if (JFactory::getApplication()->input->get( 'option' ) == 'com_hikashop' 
	|| JModuleHelper::getModule( 'mod_hikashop' )
	){
		$document->addStyleSheet($yj_site.'css/customhikashop.css');
}

/* Background switch */
$backgroundType   		= $this->params->get("backgroundType");
$bodybgcolor      		= $this->params->get("bodybgcolor");
$defaultPattern			= $this->params->get("defaultPattern");
$defaultbgImage			= $this->params->get("defaultbgImage");
$layoutType				= $this->params->get("layoutType");

$pagePrefix				= $this->params->get("pagePrefix");
if(!empty($pagePrefix)){
	$pagePrefix				= ' '.$pagePrefix;
}
$patternClass		='';
$backgroundClass	='';
$isbgType			='';

// pattern bg
if($layoutType == 2 && !empty($defaultPattern) && $backgroundType == 'pattern'){
	$patternBG 				= $yj_base. 'templates/' . $this->template.'/images/patterns/'.$defaultPattern;
	$backgroundClass		= substr($defaultPattern, 0, -4);
	$isbgType				=' ispattern';				
	$cc_css 				.= "body.".$backgroundClass.",.".$backgroundClass."{background-color:".YjsgImgTorgb($patternBG,10,10).";background-image: url(".$patternBG.");}";

}
// image bg
if($layoutType == 2 && !empty($defaultbgImage) && $backgroundType == 'image'){
	$imageBG 				= $yj_base. 'templates/' . $this->template.'/images/backgrounds/'.$defaultbgImage;
	$backgroundClass		= substr($defaultbgImage, 0, -4);
	$isbgType				=' isimage';	
	$cc_css 				.= "body.".$backgroundClass.",.".$backgroundClass."{background-color:".YjsgImgTorgb($imageBG,10,10).";background-image: url(".$imageBG.");}";
}
// color bg
if($layoutType == 2 && !empty($bodybgcolor) && $backgroundType == 'color'){
	
	$cc_css 				.= "body#stylef".$default_font_family."{background-color:".$bodybgcolor.";background-image:none;}";
}
// layout type
if($layoutType == 2){
	
	$layoutClass= 'yjsgsitew';
}else{
	$layoutClass= 'fullwidth';
}

/* Out divs */
$yjsg1_before     ='<div class="yjsg1-out">';
$yjsg1_after      ='</div>';

$yjsg5_before     ='<div class="yjsg5-out">';
$yjsg5_after      ='</div>';

/*Scroll effect*/
$scrolleffect				= $this->params->get("scrolleffect");
if($scrolleffect == 1){	
	$YjsgCustomJS[] = $yj_site.'src/scrollreveal.js';
}

?>